pipeline {
    agent any
stages {
       
        }
    stage('cleaning stage') {
             steps {
              sh "mvn clean test" 
               sh'mvn javadoc:aggregate'
       
                
        
        
    } 
   
}    

}
